### ISSUE TITLE
`option.frail` not working

### ISSUE THREAD

**Issue by alexander-akait** [remarkjs/gulp-remark#6]
@denysdovhan
https://github.com/denysdovhan/gulp-remark/issues/5#issuecomment-190766723

Gulp not exit with code > 0

``` javascript
'use strict';

var options = require('../options');
var taskConfig = options.get('tasks.remarkLint');

if (!taskConfig.enable) {
    return;
}

var gulp = require('gulp');
var gulpPlumber = require('gulp-plumber');
var gulpRemark = require('gulp-remark');
var gulpRemarkLint = require('remark-lint');
var definingConfiguration = require('../lib/defining-configuration');
var path = require('path');
var fs = require('fs');
var remarkLintOptions = JSON.parse(fs.readFileSync(path.join(process.cwd(), '.remarkrc'), 'utf8'));

function remarkLintTask() {
    var config = this.config;

    return gulp
        .src(config.paths.src.globs, config.paths.src.options)
        .pipe(gulpPlumber(config.options.plumber))
        .pipe(gulpRemark({detectRC: false, frail: true}).use(gulpRemarkLint, remarkLintOptions.plugins.lint));
}

gulp.task('remarkLint', definingConfiguration(taskConfig, remarkLintTask));

module.exports = remarkLintTask;
```

Output:

```
/some/path/to/README.md
       27:3  warning  Incorrect indentation before bullet: remove 2 spaces  list-item-bullet-indent
       27:3  warning  Incorrect indentation before bullet: remove 2 spaces  list-item-bullet-indent

⚠ 2 warnings
[18:45:21] Finished 'remarkLint' after 7.03 s
```

**Comment by denysdovhan** [comment]
Confirmed. Fixing this…

**Comment by denysdovhan** [comment]
@wooorm I can fix it only in **gulp-remark**, but maybe better to throw error in remark, [here](https://github.com/wooorm/remark/blob/b14c83f93f38d474dda6bf226a62ea8b9e8988b2/lib/cli/index.js#L38-L43)? Then I will check it in **gulp-plugin** and pass to **gulp**?

**Comment by alexander-akait** [comment]
@denysdovhan may be look how another gulp plugins work (example `gulp-eslint`)

**Comment by wooorm** [comment]
@denysdovhan, that’s not possible, it uses a callback exactly because we don’t want to throw errors!

Instead, check the `second` value for [`done`](https://github.com/wooorm/remark/blob/b14c83f93f38d474dda6bf226a62ea8b9e8988b2/lib/cli/index.js#L45) to detect if remark has “failed”, which [isn’t handled yet](https://github.com/denysdovhan/gulp-remark/blob/c96dbde19c9c6124ed5f487e156d4d46f07b80b1/index.js#L34).

**Comment by denysdovhan** [comment]
@wooorm okay, I've got it. Thank you for help.

**Comment by denysdovhan** [comment]
Done. @evilebottnawi please check.
