### ISSUE TITLE
`options.detectRC` not working

### ISSUE THREAD

**Issue by alexander-akait** [remarkjs/gulp-remark#7]
@denysdovhan 
Always `true` https://github.com/denysdovhan/gulp-remark/blob/master/index.js#L15

``` javascript
'use strict';

var options = require('../options');
var taskConfig = options.get('tasks.remarkLint');

if (!taskConfig.enable) {
    return;
}

var gulp = require('gulp');
var gulpPlumber = require('gulp-plumber');
var gulpRemark = require('gulp-remark');
var gulpRemarkLint = require('remark-lint');
var definingConfiguration = require('../lib/defining-configuration');

function remarkLintTask() {
    var config = this.config;

    return gulp
        .src(config.paths.src.globs, config.paths.src.options)
        .pipe(gulpPlumber(config.options.plumber))
        .pipe(gulpRemark({detectRC: false})/*.use(gulpRemarkLint, config.options.remarkLint)*/);
}

gulp.task('remarkLint', definingConfiguration(taskConfig, remarkLintTask));

module.exports = remarkLintTask;
```

``` json
{
    "plugins": {
        "lint": {
            "external": [],
            "reset": false,
            "blockquote-indentation": 4,
            "checkbox-character-style": {
                "checked": "x",
                "unchecked": " "
            }
        }
    }
}
```

`.remarkrc` loaded and runs all plugins.

**Comment by denysdovhan** [comment]
woooops, that's my fault :worried:

just one second.

**Comment by denysdovhan** [comment]
Fixed. Should work.

**Comment by wooorm** [comment]
Nice! :+1:

**Comment by alexander-akait** [comment]
@denysdovhan @wooorm  not working. Because `detectRC` not settings, it is property of cli class.

https://github.com/denysdovhan/gulp-remark/blob/master/index.js#L14

``` javascript
const cli = new CLI({
    settings: options,
    cwd:      process.cwd(),
    stdout:   process.stdout,
    stderr:   process.stderr,
    detectRC: false
  });
```

May be write tests? many bugs

**Comment by denysdovhan** [comment]
@wooorm `detectRC` is `true` as default? Am I right?

**Comment by denysdovhan** [comment]
@evilebottnawi try `1.1.3`

**Comment by alexander-akait** [comment]
@denysdovhan not working. `console.log(cli); process.exit();` in https://github.com/denysdovhan/gulp-remark/blob/master/index.js#L22 and see.

**Comment by denysdovhan** [comment]
@evilebottnawi fixed in `1.1.4`. Please check.

**Comment by alexander-akait** [comment]
@denysdovhan not working. It is a mockery? Try to pass params `detectRC: false` and look to run or not run plugins.

**Comment by denysdovhan** [comment]
@evilebottnawi I've tried this. It works for me. What the version of node are you using?

**Comment by alexander-akait** [comment]
@denysdovhan last

**Comment by denysdovhan** [comment]
Can't reproduce. Works fine for me.

### `detectRC: true`

![image](https://cloud.githubusercontent.com/assets/3459374/13476030/85b13534-e0ce-11e5-9e3a-29239742596c.png)

### `detectRC: false`

![image](https://cloud.githubusercontent.com/assets/3459374/13476064/b3180142-e0ce-11e5-9db5-a583a6f346ba.png)

---

`1.1.5` — is a version with polyfill for `Object.assign()` for old versions of node. There aren't any changes since `1.1.4`.

**Comment by alexander-akait** [comment]
@denysdovhan you say that if i set `detectRC: false` plugins not run, but i see other behaviour

**Comment by denysdovhan** [comment]
@evilebottnawi show your code. I can't reproduce it. Everything works fine for me.

I'm gonna write some test to cover this behavior.
