### ISSUE TITLE
frail not working with `gulpRemark().use(plugin[, options])`

### ISSUE THREAD

**Issue by alexander-akait** [remarkjs/gulp-remark#8]
``` javascript
.pipe(gulpRemark({detectRC: false, frail: true}).use(gulpRemarkLint, config.options.remarkLint));
```

**Comment by wooorm** [comment]
Please provide more detailed what you’re using, such as version numbers, applicable files, etc.
And, what results you are getting, and what you expected.

**Comment by alexander-akait** [comment]
@wooorm last version of plugin, use remark-lint on files to check their.

``` output
[13:54:38] Starting 'remarkLint'...
/path_to_file/README.md
       26:1  warning  Remove 1 line before node   no-consecutive-blank-lines

⚠ 1 warning
/path_to_file/LICENSE.md: no issues found
[13:54:38] Finished 'remarkLint' after 127 ms
```

Expected throw error, i run this on CI.

**Comment by wooorm** [comment]
@denysdovhan any idea why this isn’t working?

**Comment by denysdovhan** [comment]
@wooorm nope, I can't fix it just now. I have a small troubles with my laptop.
